name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        coverage --omit=tests/ run -m pytest --ignore=AI/ --ignore=gameLogic/ --ignore=helper/ --doctest-modules --junitxml=junit/test-results.xml
        coverage report -m
          
          
          
          
          
      
      
      
      
      
      
      
      